### ISSUE TITLE
Images  disappearing in 'medium' Adapt.device.screenSize

### ISSUE THREAD

**Issue by zarek3333** [nachocinalli/adapt-stepsGraphic#1]
Great component many thanks for creating and sharing.  One issue I am having is that all the images ex."<templates.image {..._graphic}" out of the .jsx file are disappearing when the Adapt.device.screenSize is equal to 'medium'. If it is large or small all images appear but not medium? Never seen this one before?

**Comment by nachocinalli** [comment]
For a medium screen size, you should see the small graphic.  Make sure that both the large and small images are in components.json.
Which version of framework are you using?

**Comment by zarek3333** [comment]
So looks like it is dropping the images on medium mobile size because you need to input the medium image asset in the properties.schema which doesn't exist. It is similar to how you add a block background image in Framework 5.

![medium](https://user-images.githubusercontent.com/53020396/221355677-c170d158-4af7-40df-bd94-f0fd255da4b3.jpg)

**Comment by nachocinalli** [comment]
The medium property is not needed in the properties.schema.
Like the [graphic component](https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/example.json#L12), the stepsGraphic component does not have a medium property for the graphic.

Can you update the framework to version 5.17.5 or higher?

Make sure you have updated the[ image.jsx](https://github.com/adaptlearning/adapt-contrib-core/blob/master/templates/image.jsx#L13) template.

**Comment by zarek3333** [comment]
I was on framework Ver 5.15.5 so thanks for mentioning that did the trick!
